version: '3.9'

services:

  db:
    image: postgres:15
    container_name: restaurant_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0986
      POSTGRES_DB: theCommons
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - spring_network

  app:
    build: .
    container_name: restaurant_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/theCommons
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0986
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - spring_network

volumes:
  pgdata:

networks:
  spring_network: